# Generated by Django 2.2 on 2021-03-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='author',
        ),
    ]
