# Generated by Django 2.2 on 2021-03-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0005_remove_people_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='author',
            new_name='person',
        ),
    ]
