# Generated by Django 2.2 on 2021-03-05 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('People', '0006_auto_20210305_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='person',
        ),
        migrations.AddField(
            model_name='people',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
